### PR TITLE
Modifications to stackgraph generation for Prescient

### PR DESCRIPTION
**Pull request by bknueven**
- adding over-generation
- resolving warning from matplotlib

### CODE REVIEW

**Comment by jeanpaulwatson** [comment]
Why is this a WIP/draft?

**Comment by bknueven** [comment]
I'm actively working on resolving https://github.com/grid-parity-exchange/Prescient/issues/14, and I thought we should hold-off merging until I had a PR open on Prescient, in case more changes were needed to the stackgraphs.

**Comment by bknueven** [comment]
stackgraph_2020-07-12
Here's a sample stack graph generated by prescient which captures the new over generation overlay.

**Review by jeanpaulwatson — APPROVED** [review]
Looks good - and thanks for adding the example graphic. My only complaint would be that the yellows are starting to blur, but I don't have a better recommendation. One possible recommendation would be to threshold to epsilon (this would apply to multiple categories) within zero, to avoid emitting a impossible-to-discern band for the corresponding category.

**Comment by bknueven** [comment]
I agree about the yellows blurring -- although it also helps me with at first glace to see what's happening (yellow==bad). It's also the case the over generation will above the load/demand curve and load shedding will be under it.

I'm not sure I'm a fan of thresholding these values -- even if one or the other is small, it probably means that LMPs are at extreme values at some time period that day.

**Pull request merged**
