### PR TITLE
[WIP] Stack graph generation enhancements

### PR DESCRIPTION
**Pull request by rconcep**
# Dual fuel generators
* Recognizing dual fuel generators (aux_fuel_capable == True) and stacking separately
* Indicating when aux fuel is in use
* TODO: Apply these enhancements for all display modes (show individual generators in stack components, show individual generators)

# Other enhancements
* Fixing an issue where the y-axis max limit was set to exactly the tallest stack's height

### CODE REVIEW

**Comment by rconcep** [comment]
Sneak peek. I split up generation for dual fuel generators depending on if aux fuel is being consumed. Then I plot the share of generation from generators on aux fuel on top of the share from primary fuel only.

dual_fuel

**Comment by jwatsonnm** [comment]
Can you comment on what the "dotted" (for lack of a better term) annotations for the dual-fuel represent?

**Comment by rconcep** [comment]
Yeah, it's the portion of generation from dual fuel generators that are operating using auxiliary fuel at the time. In other words, if a dual fuel generator at time t is consuming any aux. fuel, its contribution to the stack at time t will be hatched (with the dot pattern, currently).

I can add an additional legend entry although I'm concerned the legend is getting quite long. The hatching also combines with the quickstart hatching, if applicable.

**Comment by jwatsonnm** [comment]
Thanks. That's what I thought - just wanted confirmation. I would not add / clutter the legend any further, per the reasons you indicate.

**Comment by rconcep** [comment]
I'm going to close this PR and reopen a clean version.

**Pull request closed without merging**
