### PR TITLE
New solve function, test scripts, and data load features

### PR DESCRIPTION
**Pull request by anyacastillo**
This code update has the following main features:
1. New solve function calls for all models. 
2. Moved common solver call to common/solver_interface.py. 
3. Created read_from_json and write_to_json methods for ModelData.
4. Created functions in tx_calc to determine vm and va from a rectangular OPF model.
5. Orientated the power balance constraints to compute the correct dual value signs; made a NOTE for each occurrence in the function comment banners.
6. Included test scripts for the dispatch models.
7. Updated "economic dispatch" model to be titled "copperplate dispatch" model.

### CODE REVIEW

**Comment by bknueven** [comment]
I like the new data-loader functions; I should probably update the unit commitment testers to use those!

One question I have: looking at the diff for egret/models/unit_commitment.py I see some of the docstrings for a few of the uc model builder functions have the description removed. These docstrings need to be improved, but maybe that should be a separate PR?

**Comment by bknueven** [comment]
One other thing: I assume the sign changes are to get the "right" dual values. We should make sure what we're doing on PR #21 is consistent with this.

**Comment by anyacastillo** [comment]
> One other thing: I assume the sign changes are to get the "right" dual values. We should make sure what we're doing on PR #21 is consistent with this.

Yes, that's correct. I noticed that we had the wrong orientation implemented in our master branch of private egret.

**Comment by anyacastillo** [comment]
> I like the new data-loader functions; I should probably update the unit commitment testers to use those!
> 
> One question I have: looking at the diff for egret/models/unit_commitment.py I see some of the docstrings for a few of the uc model builder functions have the description removed. These docstrings need to be improved, but maybe that should be a separate PR?

Oh no, I didn't mean to remove the docstring descriptions -- actually what was happening for me was that there was a non-ascii character error caused by the comment block when I ran the code from the pycharm console, which I wasn't getting from CLI. We should revert that change I made.

**Comment by bknueven** [comment]
> there was a non-ascii character error caused by the comment block when I ran the code from the pycharm console

Ah, that's interesting. If it's alright I'll push to this branch and revert the change while removing the non-ascii characters.

**Comment by carldlaird** [comment]
Do we know what is causing these non-ascii characters? I have seen these crop up at times as well.

**Comment by bknueven** [comment]
@carldlaird I think they're just caused by a copy-paste I did with a few author's names in docstrings.

**Comment by carldlaird** [comment]
Ah, that makes sense. Good to know it is not one of our editors or something "causing" it.

**Pull request closed without merging**
