### PR TITLE
removing xvfb from travis.yml because we dont use a gui

### PR DESCRIPTION
**Pull request by michaelbynum**

### CODE REVIEW

**Comment by bknueven** [comment]
So this failed because the current tests for the viz rely on a running X session (as matplotlib.pyplot does by default).

I think we should fix the viz to not need a running X session. A common use case would be to run (and generate stack graphs) on a computer without a windowing environment. Thoughts?

**Comment by carldlaird** [comment]
Ok, if I understand correctly, we are using a different matplotlib backend if X is not present?

**Comment by bknueven** [comment]
Exactly, and specifically a backend that basically does nothing if you ask it to send something to the screen (like call `plt.plot()`). But it still allows you to write figures to the disk.

**Comment by carldlaird** [comment]
Can I merge this now?

**Comment by bknueven** [comment]
Yep

**Pull request merged**
