### PR TITLE
UC power flow integration

### PR DESCRIPTION
**Pull request by anyacastillo**
[WIP] For Ben to integrate UC with power flows

### CODE REVIEW

**Comment by michaelbynum** [comment]
@anyacastillo Is this still WIP? Just checking.

**Comment by bknueven** [comment]
@michaelbynum I think this is ready to go.

**Comment by michaelbynum** [comment]
@bknueven @anyacastillo Is there any way to reuse the dcopf code instead of reimplementing it in unit_commitment/power_balance.py?

**Comment by bknueven** [comment]
> @bknueven @anyacastillo Is there any way to reuse the dcopf code instead of reimplementing it in unit_commitment/power_balance.py?

Yes, though it would fragment the dcopf code. Besides not adding the objective, the dcopf code in unit_commitment/power_balance.py doesn't add any generator variables, as these are handled in other unit commitment code. Further, we don't want the dcopf for generator variables as it would set the lower bound at p_min, forcing every generator on.

The function pg_expr_rule handles the interface between unit commitment and dc power flow. As the opf models don't know about things like storage, this seemed like the best approach.

**Comment by michaelbynum** [comment]
That makes sense. Thanks.

**Pull request merged**
